### ISSUE TITLE
About EmotionsoiD ps2 emu tester.

### ISSUE THREAD

**Issue by Fadi5555** [Embrendassy/EmotionSoiD#1]
Thank you Embrendassy so much to make an ps2 emu on our devices.
This is our dream to play on go on our devices.

I think you have many knowledge about it. You can make a good progress about iOS port.
You said you have a repo? Do you mean on Cydia? I have cydia. Can you give me?
It's my pleasure to be a tester for you. and give you a report of issues.
If this help: I have a newest Apple device. (iPad Air 2 jailbroken) with A8X Chip and 2 GB ram. Also Ppsspp running pretty much good and fullspeed on it.
Also I think if someone make a port of dolphin emu it'll run faster than newest android devices.

Thank you for your all your hard work.

**Comment by Embrendassy** [comment]
Thanks for your interest, but much work still needs to be done and I need to finish committing the rest of the source here. I have Cydia repositories but that's irrelevant because the emulator can't currently run barely even homebrew yet. When I finish straightening out some of the code and the rest of the emulator is up, then I will make branches for Android and iOS and implement those. It will take a while though, so don't expect results or progress soon.

**Comment by Fadi5555** [comment]
I really appreciate that. And all your hard work you.
Please do your best to make it.
We will waiting for your amazing project of this.
My hope is as I told you if you need anything please tell me.
I'm ready to your special tester to give my own result about it.
Last thing. please can you give me your cydia repo to see your amazing project and see the progress step by step. Even it's not working yet but I just want follow yours.
Keep your doing up.
Good luck my bro....
